baseURL = "https://docs.influxdata.com/"
languageCode = "en-us"
title = "InfluxDB Documentation"

# Git history information for lastMod-type functionality
enableGitInfo = true

# Syntax Highlighting
pygmentsCodefences = true
pygmentsUseClasses = true

# Preserve case in article tags
preserveTaxonomyNames = true

# Generate a robots.txt
enableRobotsTXT = true

# Markdown rendering options
[blackfriday]
hrefTargetBlank = true
smartDashes = false

[taxonomies]
  "influxdb/v2.7tag" = "influxdb/v2.7/tags"
  "influxdb/v2.6/tag" = "influxdb/v2.6/tags"
  "influxdb/v2.5/tag" = "influxdb/v2.5/tags"
  "influxdb/v2.4/tag" = "influxdb/v2.4/tags"
  "influxdb/v2.3/tag" = "influxdb/v2.3/tags"
  "influxdb/v2.2/tag" = "influxdb/v2.2/tags"
  "influxdb/v2.1/tag" = "influxdb/v2.1/tags"
  "influxdb/v2.0/tag" = "influxdb/v2.0/tags"
  "influxdb/cloud/tag" = "influxdb/cloud/tags"
  "influxdb/cloud-iox/tag" = "influxdb/cloud-iox/tags"
  "influxdb/cloud-dedicated/tag" = "influxdb/cloud-dedicated/tags"
  "flux/v0.x/tag" = "flux/v0.x/tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
