plugins:
  - '../../openapi/plugins/docs-plugin.cjs'
extends:
  - recommended
  - docs/all
x-influxdata-product-name: InfluxDB 3 Core

apis:
  v3@3:
    root: v3/ref.yml
    x-influxdata-docs-aliases:
      - /influxdb3/core/api/
      - /influxdb3/core/api/v1/
      - /influxdb3/core/api/v2/
      - /influxdb3/core/api/v1-compatibility
      - /influxdb3/core/api/v2-compatibility
