plugins:
  - '../../openapi/plugins/docs-plugin.cjs'
extends:
  - recommended
  - docs/all
x-influxdata-product-name: InfluxDB 3 Cloud Dedicated

apis:
  v2@2:
    root: v2/ref.yml
    x-influxdata-docs-aliases:
      - /influxdb3/cloud-dedicated/api/
      - /influxdb3/cloud-dedicated/api/v1/
      - /influxdb3/cloud-dedicated/api/v2/
      - /influxdb3/cloud-dedicated/api/v1-compatibility
      - /influxdb3/cloud-dedicated/api/v2-compatibility
