plugins:
  - '../../openapi/plugins/docs-plugin.js'
extends:
  - recommended
  - docs/all
x-influxdata-product-name: InfluxDB v2 OSS

apis:
  '@2':
    root: ref.yml
    x-influxdata-default: true
  v1-compatibility@2:
    root: v1-compatibility/swaggerV1Compat.yml
